#!/bin/sh


scheme=$1
hostname=$2
dir=$3
junit_report=$4

echo "dir: '$dir'"

run_hurl_file() {
    local file=$1
    local series="series-$(date '+%Y-%m-%d')-$((RANDOM))"
    local release="release-$((RANDOM))"
    echo "\t: ${scheme}://${hostname} vars: series=${series}, release=${release}"
    hurl --test \
         --report-junit $junit_report \
         --variable scheme="$scheme" \
         --variable host_name="$hostname" \
         --variable series="${series}" \
         --variable release="${release}" \
         $file
}

for f in $(find "$dir" -type f -name "*.hurl"); do
    echo "RUNNING: $f"
    run_hurl_file $f
done