#!/bin/sh

# Set the maximum wait time in seconds
max_wait=60

url="$1"

# Start time
start_time=$(date +%s)

while true; do
    response_code=$(curl -s -o /dev/null -w "%{http_code}" "$url")

    if [ "$response_code" -eq 200 ]; then
        echo "Service up! HTTP Response Code: $response_code"
        break
    fi

    current_time=$(date +%s)
    elapsed_time=$((current_time - start_time))

    if [ "$elapsed_time" -ge "$max_wait" ]; then
        echo "Timeout! More than $max_wait seconds have elapsed."
        break
    fi

    # Sleep for a short duration before the next query
    sleep 2
done
